DROP TABLE alarm_events IF EXISTS;
DROP TABLE alarm_limits IF EXISTS;
DROP TABLE vital_samples IF EXISTS;
DROP TABLE adt_events IF EXISTS;
DROP TABLE pet_admissions IF EXISTS;
DROP TABLE vet_specialties IF EXISTS;
DROP TABLE vets IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE pets IF EXISTS;
DROP TABLE types IF EXISTS;
DROP TABLE owners IF EXISTS;


CREATE TABLE vets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR(30)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL
);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

CREATE TABLE types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE owners (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR_IGNORECASE(30),
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20)
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE pets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(30),
  birth_date DATE,
  type_id    INTEGER NOT NULL,
  owner_id   INTEGER NOT NULL
);
ALTER TABLE pets ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE pets ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INTEGER NOT NULL,
  visit_date  DATE,
  description VARCHAR(255)
);
ALTER TABLE visits ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
CREATE INDEX visits_pet_id ON visits (pet_id);

CREATE TABLE pet_admissions (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id             INTEGER NOT NULL,
  status             VARCHAR(20) NOT NULL,
  admitted_at        TIMESTAMP NOT NULL,
  discharged_at      TIMESTAMP,
  ward               VARCHAR(80),
  cage               VARCHAR(80),
  device_uuid        VARCHAR(100),
  responsible_vet_id INTEGER,
  latest_heart_rate  INTEGER,
  last_vital_at      TIMESTAMP
);
ALTER TABLE pet_admissions ADD CONSTRAINT fk_pet_admissions_pets FOREIGN KEY (pet_id) REFERENCES pets (id) ON DELETE RESTRICT;
CREATE INDEX pet_admissions_pet_id ON pet_admissions (pet_id);
CREATE INDEX pet_admissions_device_uuid ON pet_admissions (device_uuid);

CREATE TABLE adt_events (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correlation_id VARCHAR(100) NOT NULL UNIQUE,
  admission_id   INTEGER NOT NULL,
  event_type     VARCHAR(20) NOT NULL,
  pet_id         INTEGER NOT NULL,
  occurred_at    TIMESTAMP NOT NULL
);
ALTER TABLE adt_events ADD CONSTRAINT fk_adt_events_admissions FOREIGN KEY (admission_id) REFERENCES pet_admissions (id) ON DELETE RESTRICT;

CREATE TABLE vital_samples (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admission_id INTEGER NOT NULL,
  metric       VARCHAR(20) NOT NULL,
  sample_value INTEGER,
  sampled_at   TIMESTAMP NOT NULL
);
ALTER TABLE vital_samples ADD CONSTRAINT fk_vital_samples_admissions FOREIGN KEY (admission_id) REFERENCES pet_admissions (id) ON DELETE RESTRICT;
CREATE INDEX vital_samples_admission ON vital_samples (admission_id, sampled_at);

CREATE TABLE alarm_limits (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admission_id INTEGER NOT NULL,
  metric       VARCHAR(20) NOT NULL,
  low_extreme  INTEGER NOT NULL,
  low          INTEGER NOT NULL,
  high         INTEGER NOT NULL,
  high_extreme INTEGER NOT NULL
);
ALTER TABLE alarm_limits ADD CONSTRAINT fk_alarm_limits_admissions FOREIGN KEY (admission_id) REFERENCES pet_admissions (id) ON DELETE RESTRICT;
CREATE INDEX alarm_limits_admission ON alarm_limits (admission_id);

CREATE TABLE alarm_events (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admission_id  INTEGER NOT NULL,
  metric        VARCHAR(20) NOT NULL,
  level         VARCHAR(10) NOT NULL,
  state         VARCHAR(10) NOT NULL,
  started_at    TIMESTAMP NOT NULL,
  ended_at      TIMESTAMP,
  trigger_value INTEGER,
  acked_by      VARCHAR(80),
  acked_at      TIMESTAMP
);
ALTER TABLE alarm_events ADD CONSTRAINT fk_alarm_events_admissions FOREIGN KEY (admission_id) REFERENCES pet_admissions (id) ON DELETE RESTRICT;
CREATE INDEX alarm_events_admission ON alarm_events (admission_id, state);
